### ISSUE TITLE
error 200

### ISSUE THREAD

**Issue by saju01** [ptz0n/homebridge-verisure#105]
homebridge-verisure] Error: Cookie missing from response: HTTP 200
Preparing Advertiser for 'homebridge-verisure 1369' using bonjour-hap backend!
Starting to advertise 'homebridge-verisure 1369' using bonjour-hap backend!
[3/11/2021, 12:21:41 PM] Homebridge v1.3.3 (homebridge-verisure) is running on port 48769.

can you help me fix this

**Comment by ptz0n** [comment]
Thanks for reaching out! This cryptic error is due to Verisure starting to enroll MFA/2-step verification. Please see this new section of the readme: [Multi-factor authentication](https://github.com/ptz0n/homebridge-verisure#multi-factor-authentication)

Feel free to reach out again if you still run into issues or have any questions.

**Comment by ptz0n** [comment]
Let's discuss the feature here: https://github.com/ptz0n/homebridge-verisure/discussions/107

**Comment by ptz0n** [comment]
Just want to inform you that `v1.14.0` have been released with support for MFA. Have a lovely Wednesday 🎉
