### ISSUE TITLE
Possibility to hide change state for alarm?

### ISSUE THREAD

**Issue by mannesson** [ptz0n/homebridge-verisure#63]
Is it possible to hide state change for the alarm? I find it insecure to have that as a switch in Home on iOS.

**Comment by ptz0n** [comment]
Thanks for creating this issue. I’m not sure I understand the problem. If you don’t want the alarm accessory, simply remove the alarm code from your config.

The device must be unlocked in order to view & control the alarm state using the Home app. It’s always recomended to use a passcode for your device.

**Comment by mannesson** [comment]
I wasn't aware of that you needed to provide a valid passcode in order to change the arm state of the alarm on "Mina sidor". I thought that if you found my credentials somehow, you would be able to unarm my home alarm that way. I decided to created a user to my Verisure system that Homebridge uses without a passcode so that user can't change the arm state at all. So there is no need to do any changes to your fantastic program.
